security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    jwt_provider:
      lexik_jwt: ~

  firewalls:
    login:
      pattern: ^/api/auth/login-user
      stateless: true
      security: false

    register:
      pattern: ^/api/auth/register-user
      stateless: true
      security: false

    validate_token:
      pattern: ^/api/validate-token
      stateless: true
      jwt: ~
      provider: jwt_provider

  access_control:
    - { path: ^/api/auth/register-user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/auth/login-user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/validate-token, ips: ['%env(VALIDATION_ALLOWED_IPS)%'], roles: IS_AUTHENTICATED_FULLY }
