parameters:
  users_service_url: '%env(USERS_SERVICE_URL)%'
  jwt_secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  jwt_public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  jwt_passphrase: '%env(JWT_PASSPHRASE)%'

services:
  Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'
  _defaults:
    autowire: true
    autoconfigure: true

  Lcobucci\JWT\Signer\Key\InMemory:
    factory: ['Lcobucci\JWT\Signer\Key\InMemory', 'file']
    arguments:
      - '%env(resolve:JWT_PUBLIC_KEY)%'

  Lcobucci\JWT\Signer\Rsa\Sha256: ~

  Lcobucci\JWT\Validation\Constraint\SignedWith:
    arguments:
      - '@Lcobucci\JWT\Signer\Rsa\Sha256'
      - '@Lcobucci\JWT\Signer\Key\InMemory'

  Lcobucci\JWT\Validation\Validator: ~

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\EventListener\ApiExceptionListener:
    tags: 
      - { name: kernel.event_listener, event: kernel.exception }