parameters:
  users_service_base_url: '%env(USERS_SERVICE_BASE_URL)%'
  jwt_secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  jwt_public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  jwt_passphrase: '%env(JWT_PASSPHRASE)%'

services:
  Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'
  _defaults:
    autowire: true
    autoconfigure: true

  # Clé publique pour la vérification des JWT
  Lcobucci\JWT\Signer\Key\InMemory:
    factory: ['Lcobucci\JWT\Signer\Key\InMemory', 'file']
    arguments:
      - '%env(resolve:JWT_PUBLIC_KEY)%' # Charge le contenu du fichier de clé publique

  # Algorithme RSA pour la vérification
  Lcobucci\JWT\Signer\Rsa\Sha256: ~

  # Contrainte SignedWith pour vérifier la signature
  Lcobucci\JWT\Validation\Constraint\SignedWith:
    arguments:
      - '@Lcobucci\JWT\Signer\Rsa\Sha256'
      - '@Lcobucci\JWT\Signer\Key\InMemory'

  # Validator pour la validation des tokens
  Lcobucci\JWT\Validation\Validator: ~

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
